'use strict';

const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const hideModal = document.querySelector('.close-modal');
const showModal = document.querySelectorAll('.show-modal'); // multiple html elements have the show-modal class, so all of them will be stored in a list
console.log(showModal);

const openModal = function () {
  modal.classList.remove('hidden'); // just hidden not .hidden
  overlay.classList.remove('hidden');
};

const closeModal = function () {
  modal.classList.add('hidden');
  overlay.classList.add('hidden');
};

for (let i = 0; i < showModal.length; i++)
  showModal[i].addEventListener('click', openModal);

hideModal.addEventListener('click', closeModal);
overlay.addEventListener('click', closeModal);

document.addEventListener('keydown', function (e) {
  // e stands for event, it is an object generated by javascript and it has the properties of the key entered
  if (e.key === 'Escape' && !modal.classList.contains('hidden')) closeModal();
});
